<?php
  $topicHeadings = array(
    "Purpose" => array (
      "Purpose"
    ),
    "Problem" => array (
      "Problem"
    ),
    "Project Goal" => array (
      "Goal"
    ),
    "Project Objectives" => array (
      "Objectives"
    ),
    "Project Scope" => array (
      "Scope"
    ),
    "Key Stakeholders" => array (
      "Key Stakeholders"
    ),
    "Outcomes / Success Criteria" => array (
      "Success Criteria"
    ),
    "Assumptions and Constraints" => array (
      "Assumptions",
      "Constraints"
    ),
    "Functional Requirements" => array (
      "FR-1 Ability to log into the system",
      "FR-2 Ability to View Projects",
      "FR-3 Ability to Sort Projects",
      "FR-4 Ability to view different reports",
      "FR-5 On login a confidentiality notice shall be displayed",
      "FR-6 Change their Password",
      "FR-7 Change their Email",
      "FR-8 Change their Username",
      "FR-9 Submit a new user form",
      "FR-10 Recover a lost password",
      "FR-11 Ability to View Project Reports",
      "FR-12 Print any reports generated by the website",
      "FR-13 A log of emails sent should be kept",
      "FR-14 A log of signins should be kept"
    ),
    "Non-Functional Requirements" => array (
      "NFR-1 Database access will be secure",
      "NFR-2 The database shall be modified to include login fields",
      "NFR-3 Login will be secured",
      "NFR-4 Look and feel shall match parent website",
      "NFR-5 A limited view of the family of the projects the user is a member of",
      "NFR-6 The bottom of each page should display a confidentiality notice"
    ),
    "Technical Requirements" => array (
      "TR-1 System Availability",
      "TR-2 System Speed",
      "TR-3 Access Database"
    ),
    "Use Cases" => array (
      "UC-1 Ability to log into the system",
      "UC-2 Ability to View Projects",
      "UC-3 Ability to Sort Projects",
      "UC-4 Ability to view different reports",
      "UC-5 On login a confidentiality notice shall be displayed",
      "UC-6 Change their Password",
      "UC-7 Change their Email",
      "UC-8 Change their Username",
      "UC-9 Submit a new user form",
      "UC-10 Recover a lost password",
      "UC-11 View Project Reports",
      "UC-12 Print any reports generated by the website"
    ),
    "Data Elements" => array (
      "Data Elements Info",
      "Email",
      "Username",
      "Password"
    ),
    "Definitions" => array (
      "Database Location Description"
    )
  );
  include __DIR__."/html/sidebar.php";
  include __DIR__."/html/content.php";
  $CONTENT = array();
  $CONTENT['HEAD'] = "<link rel='stylesheet' href='./docs/css/content.css'>";
  // this function sets the content as well as cleans the id list and returns a formatted string
  // always run this before running getSidebarLinks
  $CONTENT['BODY'] = getContentById($topicHeadings);
  $CONTENT['HTML_sidebar'] = getSidebarLinks($topicHeadings);
?>